okta = {
    "org_host": "<Okta Org URL i.e. https://myorg.oktapreview.com>",
    "api_token": "<Okta API Token>",
    "oidc_client_id": "<Okta OIDC App Client Id>",
    "oidc_client_secret": "<Okta OIDC App Client Secret>",
    "redirect_uri": "https://<My App URI>/oidc",
    "app_host": "https://<My App URI>",
    "post_oidc_redirect": "https://<My App URI>",
    "auth_server_id": "<Okta API AM Auth Server Id>",
    "db_file_name": "partner_portal.db",
    "spark_post_api_key": "<Spark Post API Key>",
    "partner_group_filter_prefix": "dlr_",
    "partner_group_filter_suffix": " - Admins",
    "partner_portal_label": "Dealer Portal",
    "group_query_limit": 100,
    "app_okta_group_id": "<Okta Dealer Portal General Access Group>",
    "app_title": "Dealer Partner Portal",
    "app_logo": "logo-lavender.png",
    "admin_okta_group_id": "<Okta Portal Admin Group Id>",
    "admin_okta_group_name": "Dealer Admin Approval Group",
    "user_current_group_mapping": "current_dlr",
    "user_current_group_desc_mapping": "current_pdn",
    "user_group_access_list": "dlr_list",
    "user_current_group_desc_mapping_prefix": "PDN "
}
